### ISSUE TITLE
Improve README doc

### ISSUE THREAD

**Issue by Samsonroyal** [oscakampala/oscakampala.github.io#3]
I have noticed the README still has simple boilerplate text; i would love to update it with better engaging text

**Comment by KakoozaJerry** [comment]
Please do, 

Make the relevant changes and address it in a PR then link this issue.

**Comment by Samsonroyal** [comment]
> Please do,
> 
> Make the relevant changes and address it in a PR then link this issue.

Let me embark on it. I would love to know if there is a prior content write up that can be used. 
It would make my work easier; add a label(documentation) to it.

**Comment by KakoozaJerry** [comment]
Certainly, there is no prior content write up for this before,

Maybe what you should know is that the page is displayed using github pages so we intent to have this as a single page application in order to still be able to display using them(github pages)

Also, incase you need to include some back end logic, to keep this purely front end , we will have to fetch all that data using some apis' 

The page is also automatically deployed after a successful merge to the main branch using github actions and in order to know if the page will pass those tests you can run 
`npm export`
and
`npm run build`
 before making a PR.

If this is successful then it will display your changes in production.

For more on the github actions resource , I added them to the wiki tab on this repository . There will not be any need for changes there since they were all set up well. Only changes now are with the website. The CI/CD pipeline seems to be all entirely github pages and actions

**Comment by Samsonroyal** [comment]
I already got the documentation to next js but i appreciate the gesture of sharing the links. 

Let me begin on the readme first; I will handle the site next; I would appreciate if some technical writers would join me on formulating a write up for the readme. 

I will make sure I reach out for assistance in case i hit a snag.

**Comment by KakoozaJerry** [comment]
Sure, You can look at various open source readme's and see how they structure them. A case in point is [Coqui's readme](https://github.com/coqui-ai/TTS)  

Should do the trick, any open source repository with some good number of stars is fine, Even @ht-thomas has a readme for the kozesaDB

**Comment by KakoozaJerry** [comment]
@PiusKevin3 and @bamata are also available for any questions

**Comment by Samsonroyal** [comment]
assign me the issue then and add labels to it. @KakoozaJerry
